#!/bin/bash

# Video Demo Script for Pitch++ Compiler
# This script guides you through creating the 5-minute demo video

echo "======================================================================"
echo "           PITCH++ COMPILER - VIDEO DEMO SCRIPT"
echo "======================================================================"
echo ""
echo "Total Time: 5 Minutes"
echo ""
echo "======================================================================"
echo "SEGMENT 1: Introduction (30 seconds)"
echo "======================================================================"
echo ""
echo "SAY:"
echo "  'Hello! I'm Abdullah Butt, and this is my Pitch++ compiler."
echo "   Pitch++ is a cricket-themed C++-like programming language that"
echo "   makes coding more fun and relatable for cricket enthusiasts."
echo "   In this demo, I'll show you the lexical analyzer I built using Flex.'"
echo ""
echo "SHOW:"
echo "  - Show project folder structure"
echo "  - Briefly show scanner.l, test_program.pitch, README.md"
echo ""
read -p "Press Enter when ready for next segment..."
echo ""

echo "======================================================================"
echo "SEGMENT 2: Regex Explanation (1 minute)"
echo "======================================================================"
echo ""
echo "SAY:"
echo "  'Let me explain how two of my regex patterns work.'"
echo ""
echo "DEMO 1 - IDENTIFIER Pattern:"
echo "  'First, the IDENTIFIER pattern: [A-Z]([A-Z]|[0-9])*'"
echo "  'This means identifiers must START with an uppercase letter,"
echo "   followed by any number of uppercase letters or digits.'"
echo "  'For example: RUNS, SCORE123, A1B2 are valid.'"
echo "  'But: runs (lowercase) or 123ABC (starts with digit) are invalid.'"
echo ""
echo "SHOW:"
echo "  - Open scanner.l"
echo "  - Point to IDENTIFIER regex definition"
echo "  - Show the pattern in the rules section"
echo ""
echo "DEMO 2 - NUMBER Pattern:"
echo "  'Second, the NUMBER pattern: [+-]?([0-9]+ | [0-9]*\\.[0-9]+)'"
echo "  'This accepts both integers and floats with optional signs.'"
echo "  'Examples: 123, -456, +789, 3.14, -2.5, .99 are all valid.'"
echo ""
echo "SHOW:"
echo "  - Point to NUMBER regex in scanner.l"
echo "  - Show INTEGER and FLOAT definitions"
echo ""
read -p "Press Enter when ready for next segment..."
echo ""

echo "======================================================================"
echo "SEGMENT 3: Test Program Walkthrough (1 minute)"
echo "======================================================================"
echo ""
echo "SAY:"
echo "  'Now let's look at my test program. This is a cricket match"
echo "   simulator written in Pitch++. Notice how I use cricket-themed"
echo "   keywords throughout the code.'"
echo ""
echo "HIGHLIGHT:"
echo "  - PLAY() { } - The main function (playing the match)"
echo "  - OPENER TOTALRUNS = 0~ - Integer variable declaration"
echo "  - TEXTBOOK TEAMNAME - String variable"
echo "  - OVER(...)  - For loop (cricket overs)"
echo "  - TOSS(...) - If statement (toss decision)"
echo "  - UMPIRE { } - Else statement"
echo "  - RUN('...') - Output statement (scoring runs)"
echo "  - RETIRE 0~ - Return statement"
echo ""
echo "SHOW:"
echo "  - Open test_program.pitch"
echo "  - Scroll through showing keywords"
echo "  - Point out operators: ===, +++, ---"
echo "  - Point out punctuators: ~, { }, ( )"
echo ""
read -p "Press Enter when ready for next segment..."
echo ""

echo "======================================================================"
echo "SEGMENT 4: Running the Scanner (1.5 minutes)"
echo "======================================================================"
echo ""
echo "SAY:"
echo "  'Now let's compile and run the lexical analyzer on our test program.'"
echo ""
echo "DEMO:"
echo "  1. 'First, I'll compile the scanner using make'"
echo ""
read -p "Press Enter to run: make"
echo ""
echo "RUN COMMAND: make"
echo ""
echo ""
echo "  2. 'Now I'll run the scanner on our test program'"
echo ""
read -p "Press Enter to run: make run"
echo ""
echo "RUN COMMAND: make run"
echo ""
echo ""
echo "  3. 'Let's check the token output file'"
echo ""
read -p "Press Enter to show tokens.txt"
echo ""
echo "RUN COMMAND: cat tokens.txt | head -30"
echo ""
echo "SAY:"
echo "  'As you can see, each token is identified with its type and lexeme,"
echo "   along with the line number where it appears.'"
echo ""
echo "SHOW:"
echo "  - Point out KEYWORD tokens (PLAY, OPENER, TOSS, etc.)"
echo "  - Point out IDENTIFIER tokens (TOTALRUNS, TARGET, etc.)"
echo "  - Point out NUMBER tokens (0, 150, 20, etc.)"
echo "  - Point out OPERATOR tokens (=, +, ===, +++, etc.)"
echo "  - Point out PUNCTUATION tokens (~, {, }, etc.)"
echo "  - Show the summary at the end"
echo ""
read -p "Press Enter when ready for next segment..."
echo ""

echo "======================================================================"
echo "SEGMENT 5: Error Handling Demo (1 minute)"
echo "======================================================================"
echo ""
echo "SAY:"
echo "  'Now let me demonstrate error handling. I'll add some intentional"
echo "   errors to show how the scanner detects invalid tokens.'"
echo ""
echo "DEMO:"
echo "  1. 'I'll add a lowercase identifier, which is not allowed'"
echo ""
read -p "Press Enter to create error_test.pitch"
echo ""
echo "CREATE FILE: error_test.pitch"
echo ""
echo "CONTENT:"
cat << 'EOF'
PLAY() {
    OPENER SCORE = 100~
    opener invalid = 50~
    OPENER 123ABC = 10~
    OPENER TEST@ = 5~
}
EOF
echo ""
echo ""
echo "  2. 'Now I'll run the scanner on this file with errors'"
echo ""
read -p "Press Enter to run: ./scanner error_test.pitch"
echo ""
echo "RUN COMMAND: ./scanner error_test.pitch"
echo ""
echo ""
echo "  3. 'Let's check the error log'"
echo ""
read -p "Press Enter to show errors.log"
echo ""
echo "RUN COMMAND: cat errors.log"
echo ""
echo "SAY:"
echo "  'As you can see, the scanner detected three errors:'"
echo "  '1. Line 3: opener - lowercase identifier (invalid)'"
echo "  '2. Line 4: 123 - identifier starting with number (invalid)'"
echo "  '3. Line 5: @ - invalid special character'"
echo "  'Each error is reported with its line number and the invalid token.'"
echo ""
read -p "Press Enter when ready for conclusion..."
echo ""

echo "======================================================================"
echo "SEGMENT 6: Conclusion (30 seconds)"
echo "======================================================================"
echo ""
echo "SAY:"
echo "  'To summarize, my Pitch++ lexical analyzer successfully:'"
echo "  '- Recognizes 15 cricket-themed keywords'"
echo "  '- Handles 13 operators and 7 punctuations'"
echo "  '- Tracks line numbers for every token'"
echo "  '- Provides comprehensive error detection'"
echo "  '- Supports identifiers, numbers, strings, and comments'"
echo "  ''"
echo "  'This is Phase 1 of the compiler. Future phases will include'"
echo "  'parsing, semantic analysis, and code generation.'"
echo "  ''"
echo "  'Thank you for watching! May your code compile without errors,'"
echo "  'and your innings be long!'"
echo ""
echo "SHOW:"
echo "  - Show README.md briefly"
echo "  - Show final project structure"
echo "  - Wave goodbye!"
echo ""
echo "======================================================================"
echo "                    END OF DEMO SCRIPT"
echo "======================================================================"
echo ""
echo "Total Time: ~5 minutes"
echo ""
echo "Remember to:"
echo "  - Speak clearly and at a moderate pace"
echo "  - Show your face (if comfortable) or use voiceover"
echo "  - Use screen recording software (OBS, Camtasia, etc.)"
echo "  - Keep camera steady"
echo "  - Ensure good lighting and audio"
echo "  - Edit out any long pauses"
echo ""
echo "Good luck with your video! 🏏"
echo ""

